rails/config/routes.rb
Broomble::Application.routes.draw do
  root :to => "home#index",
    :protocol => (Rails.env == "development" ? "http://localhost:3000" : "http://127.0.0.1:3000")

  get "/rss" => "home#index", :format => "rss"
  get "/hottest.json" => "home#index", :format => "json"

  get "/page/:page" => "home#index"

  get "/newest(.format)" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/newest/:user" => "home#newest_by_user"
  get "/newest/:user/page/:page" => "home#newest_by_user"

  get "/threads" => "comments#threads"
  get "/threads/:user" => "comments#threads"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  match "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password"

  match "/t/:tag" => "home#tagged", :as => "tag"
  match "/t/:tag/page/:page" => "home#tagged"

  get "/search" => "search#index"

  resources :stories do
    post "upvote"
    post "downvote"
    post "unvote"
    post "undelete"
  end
  post "/stories/fetch_url_title" => "stories#fetch_url_title"
  post "/stories/preview" => "stories#preview"

  resources :comments do
    post "upvote"
    post "downvote"
    post "unvote"

    post "edit"
    post "preview"
    post "update"
    post "delete"
    post "undelete"
  end
  get "/comments/page/:page" => "comments#index"
  post "/comments/post_to/:story_id" => "comments#create"
  post "/comments/preview_to/:story_id" => "comments#preview_new"

  get "/messages/sent" => "messages#sent"
  resources :messages do
    post "keep_as_new"
  end

  get "/s/:id/:title/comments/:comment_short_id" => "stories#show_comment"
  get "/s/:id/(:title)" => "stories#show"

  get "/u" => "users#tree"
  get "/u/:id" => "users#show"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"

  get "/moderations" => "moderations#index"
  get "/moderations/page/:page" => "moderations#index"

  get "/privacy" => "home#privacy"
  get "/about" => "home#about"
end

rails/app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories,
    :include => :user
  has_many :comments
  has_many :sent_messages,
    :class_name => "Message",
    :foreign_key => "author_user_id"
  has_many :received_messages,
    :class_name => "Message",
    :foreign_key => "recipient_user_id"
  has_many :tag_filters
  belongs_to :invited_by_user,
    :class_name => "User"

  has_secure_password

  validates :email, :format => { :with => /\A[^@ ]+@[^@ ]+\.[^@ ]+\Z/ },
    :uniqueness => { :case_sensitive => false }

  validates :password, :presence => true, :on => :create

  validates :username, :format => { :with => /\A[A-Za-z0-9][A-Za-z0-9_-]*\Z/ },
    :uniqueness => { :case_sensitive => false }

  validates_each :username do |record,attr,value|
    if BANNED_USERNAMES.include?(value.to_s.downcase)
      record.errors.add(attr, "is not permitted")
    end
  end

  attr_accessible :username, :email, :password, :password_confirmation,
    :about, :email_replies, :pushover_replies, :pushover_user_key,
    :pushover_device, :email_messages, :pushover_messages, :email_mentions,
    :pushover_mentions, :mailing_list_enabled

  before_save :check_session_token
  before_validation :on => :create do
    self.create_rss_token
    self.create_mailing_list_token
  end
  after_create :create_default_tag_filters

  BANNED_USERNAMES = [ "admin", "administrator", "hostmaster", "mailer-daemon",
    "postmaster", "root", "security", "support", "webmaster", ]

  def as_json(options = {})
    h = super(:only => [
      :username,
      :created_at,
      :is_admin,
      :is_moderator,
    ])
    h[:avatar_url] = avatar_url
    h
  end

  def avatar_url
    "https://secure.gravatar.com/avatar/" <<
      Digest::MD5.hexdigest(self.email.strip.downcase) << "?r=pg&d=" <<
      CGI.escape(Rails.application.routes.url_helpers.root_url +
      "images/1x1t.gif") << "&s=100"
  end

  def average_karma
    if (k = self.karma) == 0
      0
    else
      k.to_f / (self.stories_submitted_count + self.comments_posted_count)
    end
  end

  def check_session_token
    if self.session_token.blank?
      self.session_token = Utils.random_str(60)
    end
  end

  def create_default_tag_filters
    Tag.where(:filtered_by_default => true).each do |t|
      tf = TagFilter.new
      tf.tag_id = t.id
      tf.user_id = self.id
      tf.save
    end
  end

  def create_mailing_list_token
    if self.mailing_list_token.blank?
      self.mailing_list_token = Utils.random_str(10)
    end
  end

  def create_rss_token
    if self.rss_token.blank?
      self.rss_token = Utils.random_str(60)
    end
  end

  def comments_posted_count
    Keystore.value_for("user:#{self.id}:comments_posted").to_i
  end

  def initiate_password_reset_for_ip(ip)
    self.password_reset_token = Utils.random_str(40)
    self.save!

    PasswordReset.password_reset_link(self, ip).deliver
  end

  def karma
    Keystore.value_for("user:#{self.id}:karma").to_i
  end

  def linkified_about
    # most users are probably mentioning "@username" to mean a twitter url, not
    # a link to a profile on this site
    Markdowner.to_html(self.about, { :disable_profile_links => true })
  end

  def most_common_story_tag
    tag_id = Tagging.connection.select_one("SELECT tag_id, " <<
      "COUNT(taggings.id) AS tag_count FROM taggings LEFT OUTER JOIN " <<
      "stories ON stories.id = taggings.story_id WHERE stories.user_id = " <<
      "#{q(self.id)} GROUP BY tag_id ORDER BY tag_count DESC LIMIT 1")

    if tag_id && tag_id["tag_id"]
      Tag.where(:id => tag_id["tag_id"]).first
    else
      nil
    end
  end

  def recent_threads(amount)
    Comment.connection.select_all("SELECT DISTINCT " +
      "thread_id FROM comments WHERE user_id = #{q(self.id)} ORDER BY " +
      "created_at DESC LIMIT #{q(amount)}").map{|r| r.values.first }
  end

  def stories_submitted_count
    Keystore.value_for("user:#{self.id}:stories_submitted").to_i
  end

  def undeleted_received_messages
    received_messages.where(:deleted_by_recipient => false)
  end

  def undeleted_sent_messages
    sent_messages.where(:deleted_by_author => 0)
  end

  def unread_message_count
    Keystore.value_for("user:#{self.id}:unread_messages").to_i
  end

  def update_unread_message_count!
    Keystore.put("user:#{self.id}:unread_messages",
      Message.where(:recipient_user_id => self.id,
        :has_been_read => false).count)
  end
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @showing_user = User.find_by_username!(params[:id])
    @title = "User #{@showing_user.username}"
  end

  def tree
    @title = "Users"

    parents = {}
    karmas = {}
    User.all.each do |u|
      (parents[u.invited_by_user_id.to_i] ||= []).push u
    end

    Keystore.find(:all, :conditions => "`key` like 'user:%:karma'").each do |k|
      karmas[k.key[/\d+/].to_i] = k.value
    end

    @tree = []
    recursor = lambda{|user,level|
      if user
        @tree.push({ :level => level, :user_id => user.id,
          :username => user.username, :karma => karmas[user.id].to_i,
          :is_moderator => user.is_moderator?, :is_admin => user.is_admin? })
      end

      # for each user that was invited by this one, recurse with it
      (parents[user ? user.id : 0] || []).each do |child|
        recursor.call(child, level + 1)
      end
    }
    recursor.call(nil, 0)

    @tree
  end

  def invite
    @title = "Pass Along an Invitation"
  end
end

rails/app/views/users/_invitationform.html.erb
<p>
Invitations are unlimited, but persons you invite will be associated with your
account in the <a href="/u">user tree</a> and you may be responsible for them
if they cause problems.  Please use your discretion when inviting persons you
don't personally know.
</p>

<%= form_tag "/invitations", :method => :post do |f| %>
  <% if defined?(return_home) && return_home %>
    <%= hidden_field_tag :return_home, 1 %>
  <% end %>

  <div class="boxline">
    <%= label_tag :email, "E-mail Address:", :class => "required" %>
    <%= text_field_tag :email, "", :size => 30 %>
  </div>

  <div class="boxline">
    <%= label_tag :memo, "Memo to User:", :class => "required" %>
    <%= text_field_tag :memo, "", :size => 60 %>
  </div>

  <div class="boxline">
    <p></p>
    <%= submit_tag "Send Invitation" %>
  </div>
<% end %>

rails/app/views/users/show.html.erb
<div class="box wide">
  <div class="legend">
    <%= @showing_user.username %>
    <% if @user %>
      (<a href="/messages?to=<%= @showing_user.username %>">Send a Message</a>)
    <% end %>
  </div>

  <div id="gravatar">
    <img src="<%= @showing_user.avatar_url %>">
  </div>

  <label class="required">Status:</label>
  <span class="d">
    Active <%= @showing_user.is_admin? ? "administrator" :
      (@showing_user.is_moderator? ? "moderator" : "user") %>
  </span>
  <br>

  <label class="required">Joined:</label>
  <span class="d">
    <%= raw(time_ago_in_words_label(@showing_user.created_at)) %> ago
    <% if @showing_user.invited_by_user %>
      by invitation from
      <a href="/u/<%= @showing_user.invited_by_user.username %>"><%=
        @showing_user.invited_by_user.username %></a>
    <% end %>
  </span>
  <br>

  <label class="required">Karma:</label>
  <span class="d">
    <%= @showing_user.karma %>, averaging <%=
      number_with_precision(@showing_user.average_karma, :precision => 2) %>
      per story/comment
  </span>
  <br>

  <label class="required">Stories Submitted:</label>
  <span class="d">
    <% tag = @showing_user.most_common_story_tag %>
    <a href="/newest/<%= @showing_user.username %>"><%=
      @showing_user.stories_submitted_count %></a><%= tag ? ", " : "" %>
    <% if tag %>
      most commonly tagged <a href="<%= tag_url(tag.tag) %>"
        class="<%= tag.css_class %>" title="<%= tag.description %>"><%=
        tag.tag %></a>
    <% end %>
  </span>
  <br>

  <label class="required">Comments Posted:</label>
  <span class="d">
    <a href="/threads/<%= @showing_user.username %>"><%=
      @showing_user.comments_posted_count %></a>
  </span>
  <br>

  <label class="required">About:</label>

  <div id="user_about" class="shorten_first_p">
    <% if @showing_user.about.present? %>
      <%= raw @showing_user.linkified_about %>
    <% else %>
      <span class="na">A mystery...</span>
    <% end %>
  </div>
</div>

rails/app/views/users/tree.html.erb
<div class="box wide">
  <strong>Users (<%= User.count %>)</strong>
  <p>
  <% prev_level = 0 %>
  <% @tree.each do |u| %>
    <% if u[:level] > prev_level %>
      <ul class="<%= u[:level] == 1 ? "root" : "user_tree" %>">
    <% elsif u[:level] < prev_level %>
      <% (prev_level - u[:level]).times do %>
        </ul>
      <% end %>
    <% else %>
      </li>
    <% end %>

    <li><a href="/u/<%= u[:username] %>"><%= u[:username] %></a>
      (<%= u[:karma] %>)
      <% if u[:is_admin] %>
        (administrator)
      <% elsif u[:is_moderator] %>
        (moderator)
      <% end %>

    <% prev_level = u[:level] %>
  <% end %>
  <% prev_level.times do %>
    </ul>
  <% end %>
</div>