rails/config/routes.rb
Broomble::Application.routes.draw do
  root :to => "home#index",
    :protocol => (Rails.env == "development" ? "http://localhost:3000" : "http://127.0.0.1:3000")

  get "/rss" => "home#index", :format => "rss"
  get "/hottest.json" => "home#index", :format => "json"

  get "/page/:page" => "home#index"

  get "/newest(.format)" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/newest/:user" => "home#newest_by_user"
  get "/newest/:user/page/:page" => "home#newest_by_user"

  get "/threads" => "comments#threads"
  get "/threads/:user" => "comments#threads"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  match "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password"

  match "/t/:tag" => "home#tagged", :as => "tag"
  match "/t/:tag/page/:page" => "home#tagged"

  get "/search" => "search#index"

  resources :stories do
    post "upvote"
    post "downvote"
    post "unvote"
    post "undelete"
  end
  post "/stories/fetch_url_title" => "stories#fetch_url_title"
  post "/stories/preview" => "stories#preview"

  resources :comments do
    post "upvote"
    post "downvote"
    post "unvote"

    post "edit"
    post "preview"
    post "update"
    post "delete"
    post "undelete"
  end
  get "/comments/page/:page" => "comments#index"
  post "/comments/post_to/:story_id" => "comments#create"
  post "/comments/preview_to/:story_id" => "comments#preview_new"

  get "/messages/sent" => "messages#sent"
  resources :messages do
    post "keep_as_new"
  end

  get "/s/:id/:title/comments/:comment_short_id" => "stories#show_comment"
  get "/s/:id/(:title)" => "stories#show"

  get "/u" => "users#tree"
  get "/u/:id" => "users#show"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"

  get "/moderations" => "moderations#index"
  get "/moderations/page/:page" => "moderations#index"

  get "/privacy" => "home#privacy"
  get "/about" => "home#about"
end

rails/app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user

  attr_accessible nil

  validate do
    unless email.to_s.match(/\A[^@ ]+@[^ @]+\.[^ @]+\z/)
      errors.add(:email, "is not valid")
    end
  end

  before_validation :create_code,
    :on => :create

  def create_code
    (1...10).each do |tries|
      if tries == 10
        raise "too many hash collisions"
      end

      if !Invitation.find_by_code(self.code = Utils.random_str(15))
        break
      end
    end
  end

  def send_email
    InvitationMailer.invitation(self).deliver
  end
end

rails/app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :require_logged_in_user,
    :except => [ :build, :create_by_request, :confirm_email ]

  def build
  end

  def index
    @invitation_requests = InvitationRequest.where(:is_verified => true)
  end

  def confirm_email
    if !(ir = InvitationRequest.find_by_code(params[:code].to_s))
      flash[:error] = "Invalid or expired invitation request"
      return redirect_to "/invitations/request"
    end

    ir.is_verified = true
    ir.save!

    flash[:success] = "Your invitiation request has been validated and " <<
      "will now be shown to other logged-in users."
    return redirect_to "/invitations/request"
  end

  def create
    i = Invitation.new
    i.user_id = @user.id
    i.email = params[:email]
    i.memo = params[:memo]

    begin
      if i.save
        i.send_email
        flash[:success] = "Successfully e-mailed invitation to " <<
          params[:email].to_s << "."
      else
        raise
      end
    rescue
      flash[:error] = "Could not send invitation, verify the e-mail " <<
        "address is valid."
    end

    if params[:return_home]
      return redirect_to "/"
    else
      return redirect_to "/settings"
    end
  end

  def create_by_request
    ir = InvitationRequest.new
    ir.name = params[:name]
    ir.email = params[:email]
    ir.memo = params[:memo]

    ir.ip_address = request.remote_ip

    if ir.save
      flash[:success] = "You have been e-mailed a confirmation to " <<
        params[:email].to_s << "."
      return redirect_to "/invitations/request"
    else
      render :action => :build
    end
  end

  def send_for_request
    if !(ir = InvitationRequest.find_by_code(params[:code].to_s))
      flash[:error] = "Invalid or expired invitation request"
      return redirect_to "/invitations"
    end

    if ir.save
      i = Invitation.new
      i.user_id = @user.id
      i.email = ir.email

      if i.save
        i.send_email
        ir.destroy
        flash[:success] = "Successfully e-mailed invitation to " <<
          ir.name.to_s << "."
      end

      return redirect_to "/invitations"
    else
      render :action => :build
    end
  end
end

rails/app/views/invitations/build.html.erb
<div class="box wide">
  <div class="legend">
    Request an Invitation
  </div>

  <p>
  If you don't know (or can't find) an <a href="/u/">existing user</a> from
  which to request an invitiation, you can make a public request for one.  This
  will display your name and memo to all other logged-in users who can then
  send you an invitation if they recognize you.
  </p>
  <p>
  Your e-mail address must be valid and confirmed by visiting a URL e-mailed to
  you before your request will be displayed.  Your e-mail address will not be
  shown to any other users.
  </p>

  <%= form_tag create_invitation_by_request_url do %>
    <p>
    <%= label_tag :name, "Name:" %>
    <%= text_field_tag :name, "", :size => 30 %>
    <br />

    <%= label_tag :email, "E-mail Address:" %>
    <%= text_field_tag :email, "", :size => 30 %>
    <br />

    <%= label_tag :memo, "Memo:" %>
    <%= text_field_tag :memo, "", :size => 75 %>
    <br />
    <label></label>
    <span class="na">URL to your website, Github account, etc.</span>
    </p>

    <p>
    <%= submit_tag "Request Invitiation" %>
    </p>
  <% end %>
</div>

rails/app/views/invitations/index.html.erb
<div class="box wide">
  <div class="legend">
    Requested Invitations
  </div>

  <p>
  These persons have requested invitations and confirmed their e-mail
  addresses.  If you recognize anyone, feel free to send them an invitation and
  remove their request.  Spam will be cleared out by a moderator.
  </p>

  <table class="data" width="100%" cellspacing=0>
  <tr>
    <th width="15%">Date/Time</th>
    <th width="20%">Name</th>
    <th width="50%">Memo</th>
    <th width="15%"></th>
  </tr>
  <% bit = 0 %>
  <% @invitation_requests.each do |ir| %>
    <tr class="row<%= bit %>">
      <td><%= ir.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td><%= ir.name %></td>
      <td><%= raw ir.markeddown_memo %></td>
      <td><%= form_tag send_invitation_for_request_url, :confirm => "Are " <<
      "you sure you want to invite this person and remove this request?" do %>
        <%= hidden_field_tag "code", ir.code %>
        <%= submit_tag "Send Invitiation" %>
      <% end %></td>
    </tr>
    <% bit = (bit == 1 ? 0 : 1) %>
  <% end %>
  <% if @invitation_requests.count == 0 %>
    <tr>
      <td colspan=4 align="center"><span class="na">No invitation
        requests</span></td>
    </tr>
  <% end %>
  </table>
</div>